name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn --no-transfer-progress --batch-mode --update-snapshots verify

      - name: Test and fail on exceptions
        run: |
          set -euo pipefail
          java -jar jd-cli/target/jd-cli.jar -od /tmp/src jd-lib/target/jd-lib-*.jar 2>&1 | tee output.log
          if grep -iE "exception|error" output.log; then
            echo "Detected Exception or Error in output."
            exit 1
          fi

      - name: Upload output log
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: jd-cli-log
          path: output.log
