name: Publish

# https://github.com/marketplace/actions/upload-files-to-a-github-release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven build
        run: mvn --batch-mode clean install
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: jd-cli-*-dist.*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
